//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("3.1")]
[assembly: System.Reflection.AssemblyFileVersion("3.1.0-dev-20170926-1556.6faf7c3")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.1.0-dev-20170926-1556")]


